name: Update RSS Feed Hourly
on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allows manual run
jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run RSS script
        run: python rss_builder.py
      - name: Commit and push updates
        run: |
          git config --global http://user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@http://users.noreply.github.com"
          git add combined.xml
          git commit -m "Auto update feed" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@http://github.com/${{ github.repository }}.git main


